### ISSUE TITLE
Translate in VR

### ISSUE THREAD

**Issue by ThornsW** [IllusionMods/KoikatsuTranslation#163]
How to translate in VR mode (I want to see dialogue subtitles in VR mode)

**Comment by ManlyMarco** [comment]
Doesn't the subtitles plugin work in VR? I know for sure it at least works with VR plugins.

**Comment by ThornsW** [comment]
> Doesn't the subtitles plugin work in VR? I know for sure it at least works with plugins that add VR to main game.

Thank you for your reply, I am a player from China. The subtitle plugin works normally in VR mode, but displays the Japanese subtitle of the game itself. Just yesterday, I used dnspy to modify it and access the Chinese txt file. Now the Chinese translation problem in VR has been perfectly solved. Thank you for writing the subtitle display in the VR environment, which makes it easy for me to complete the Chinese translation. Thanks again.
